source :gemcutter

gem "rails", "2.3.8"
gem "bundler"
gem "sqlite3-ruby", :require => "sqlite3"

group :development do
  gem "annotate", :require => false
end

group :test do
  gem "rspec-rails", "1.3.2"
  gem "syntax", :require => false
end

group :cucumber do
  gem "rspec-rails", "1.3.2"
  gem "cucumber-rails", "0.3.0"
  gem "capybara"
  gem "database_cleaner"
end
