source :gemcutter

gem "rails", "2.3.8"
gem "bundler"
gem "sqlite3-ruby", :require => "sqlite3"

group :test do
  gem "rspec-rails", "1.3.2"
  gem "remarkable_rails", "3.1.13"
  gem "syntax", :require => false
end
